### ISSUE TITLE
Problem with a Proxy Server

### ISSUE THREAD

**Issue by nickmew0** [sghaskell/splunk-add-on-for-zenoss#2]
Hi, 
I'm trying to do some integration between Zenoss cloud and our on-premise Splunk instance. 
It appears due to our firewall rules and general setup, in order to get data any call to the Zenoss cloud API needs to explicitly define our proxy server as part of the call.
My understanding is that Splunk modular inputs don't read any global proxy settings, so have to be defined as part of the modular input, and unless I'm missing something I can't see any option to define the proxy server in this add-on setup.
Am I wrong, and if not is it possible to add in an option to define a proxy server to put into the call?
thanks,
Nick

**Comment by edro15** [comment]
Hi @nickmew0,

the proxy with basic authentication is supported from version 2.0.5 of the add-on. You can download it from Splunkbase. The source code is still under review (see #1). Thanks.

**Comment by nickmew0** [comment]
> Hi @nickmew0,
> 
> the proxy with basic authentication is supported from version 2.0.5 of the add-on. You can download it from Splunkbase. The source code is still under review (see #1). Thanks.

That's great - I hadn't noticed the new version 👍 I'll download and check it out

**Comment by nickmew0** [comment]
Apologies - just checked this out and on restarting Splunk I'm getting this error;
Unable to initialize modular input "zenoss_events" defined in the app "TA-zenoss": Introspecting scheme=zenoss_events: script running failed (exited with code 1)..
I seem to remember having this sometime ago with the previous version but can't remember what resolved it. We are running 
Splunk Enterprise
Version: 8.1.1
Build: 08187535c166
Splunk Add-on Builder
Version 3.0.1
App Build 2
I've attached the internal Splunkd log - looks like issues with a few libraries but may be our setup rather the add-on. Any hints on where to go with this would be great





<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/Nick/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/Nick/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/Nick/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>







·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   18/06/2021   16:22:53.107 | 06-18-2021 16:22:53.107   +0100 ERROR ModularInputs   - Unable to initialize modular input   "zenoss_events" defined   in the app   "TA-zenoss": Introspecting scheme=zenoss_events: script   running failed (exited   with code 1)..   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
-- | --
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - Introspecting scheme=zenoss_events:   script running failed   (exited with code   1).   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: ModuleNotFoundError:   No module named   'urllib2'   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: import urllib2   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: File   "/export/gcs1/splunk/etc/apps/TA-zenoss/bin/zenoss_api.py", line 12, in &lt;module&gt;   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: from zenoss_api   import ZenossAPI   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: File   "/export/gcs1/splunk/etc/apps/TA-zenoss/bin/zenoss_events.py", line 10, in &lt;module&gt;   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:52.884 | 06-18-2021 16:22:52.884   +0100 ERROR ModularInputs   - &lt;stderr&gt; Introspecting   scheme=zenoss_events: Traceback   (most recent call   last):   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log
18/06/2021   16:22:08.693 | 06-18-2021 16:22:08.693   +0100 INFO SpecFiles   - Found external   scheme definition for   stanza="zenoss_events://" from spec file="/export/gcs1/splunk/etc/apps/TA-zenoss/README/inputs.conf.spec"   with parameters="zenoss_username,   zenoss_realm, zenoss_server, no_ssl_cert_check,   cafile, device, start_date,   index_closed, index_cleared, index_archived, archive_threshold, index_suppressed, index_repeats, checkpoint_delete_threshold, tzone, proxy_uri, proxy_username, proxy_realm"   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   host =&nbsp;lonasscrbu7.uk.db.com   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   index =&nbsp;_internal   ·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   source =&nbsp;/export/gcs1/splunk/var/log/splunk/splunkd.log

**Comment by edro15** [comment]
Hi @nickmew0 ,

since there are major changes to input definition, please make sure to: 
* remove your `$SPLUNK_HOME/etc/apps/TA-zenoss/local/inputs.conf` (back it up, eventually)
* restart Splunk

Version 2.0.5 expects Zenoss credentials to be specified through the Credential Management Dashboard and does not recognise parameters such as `username` or `password` in `$SPLUNK_HOME/etc/apps/TA-zenoss/local/inputs.conf`. Valid parameters are defined in `$SPLUNK_HOME/etc/apps/TA-zenoss/README/inputs.conf.spec`. 

Hope this helps.

**Comment by nickmew0** [comment]
Hi - clearing the whole application and re-installing did the trick, Now just need to configure it. 👍
