### ISSUE TITLE
Issues connection to Zenoss

### ISSUE THREAD

**Issue by nickmew0** [sghaskell/splunk-add-on-for-zenoss#3]
Sorry to bother again - having problems with configuration of the add-on
We've proven connectivity to Zenoss from on our Splunk instance, both by using a shell curl command and using the Splunk add-on builder to test this curl command within a Splunk context; the following test will return Event data from our cloud instance of Zenoss

curl -k -x http://OURPROXY.COM:8080 https://OURDOMAIN.zenoss.eu/cz0/zport/dmd/evconsole_router -H "z-api-key: OURAPIKEY" -H "Content-Type: application/json" --data "{\"action\":\"EventsRouter\",\"method\":\"query\",\"data\":[{\"params\":{\"eventState\":[0,1,2],\"severity\":[5,3],\"firstTime\":\"1624454747\"},\"keys\":[\"eventState\", \"severity\", \"device\", \"component\", \"eventClass\", \"summary\", \"firstTime\", \"lastTime\", \"count\", \"agent\", \"evid\", \"eventClassKey\", \"message\"],\"limit\":200,\"sort\":\"device\",\"dir\":\"ASC\"}],\"type\":\"rpc\",\"tid\":17}"

However, when configuring the add-on using the same parameters  (with credentials held in credential management against the TA-Zenoss app) we are getting the message
Encountered the following error while trying to save: Failed to connect to https://OURDOMAIN.zenoss.eu and query for an event - Verify username, password and web # interface are correct

To be explicit the parameters filled in for the module input are;
Zenoss Input Name: Zenoss
Zenoss Account Name: OURUSER (where this is linked to the api token key in Credentials Management for UAT realm
Zenoss Account Realm: UAT
Zenoss Web Interface: https://OURDOMAIN.zenoss.eu
Disable SSL Certificate is ticked (our dev Splunk environment doesn't have an up to date certificate, NOTE the curl command wouldn't work without the -k option
Set Sourcetype: Manual
Sourcetype  :
Host Field Value: zenoss
Index: zenoss (which is a valid index)
Proxy URL: http://OURPROXY.COM:8080

I can't see anything obvious in the logs I can find which would give me any more information on what is going on.
Any help would be much appreciated

**Comment by edro15** [comment]
Hi @nickmew0 ,

Thanks for reaching out. To have more details about the error, you could try to apply the following changes to `$SPLUNK_HOME/etc/apps/TA-zenoss/bin/zenoss_events.py`

```
@@ -366,8 +366,9 @@ for reference")
             z = ZenossAPI(zenoss_server, username, password, proxy_uri, proxy_username, proxy_password, no_ssl_cert_check, cafile)
             events = z.get_events(None, start=0, limit=1)
         except Exception as e:
-            raise ValueError("Failed to connect to %s and query for an event - Verify username, password and web \
-# interface address are correct" % zenoss_server)
+            raise ValueError("Failed to connect to {} and query for an event. Error {}".format(zenoss_server, e))
+#             raise ValueError("Failed to connect to %s and query for an event - Verify username, password and web \
+# # interface address are correct" % zenoss_server)
```

Any luck getting more info?

**Comment by nickmew0** [comment]
Hi, thanks for coming back to me. Have changed the script and now getting the following error;

Encountered the following error while trying to save: Failed to connect to https://atosdb.zenoss.eu and query. Error Unable to complete request. HTTP Error [400]: {"action": "EventsRouter", "method": "query", "data": [{"start": 0, "limit": 1, "dir": "DESC", "sort": "severity", "archive": false, "params": {"severity": [5, 4, 3, 2], "eventState": [0, 1]}}], "type": "rpc", "tid": 1}

Looks like the Zenoss end doesn't like the call.

**Comment by edro15** [comment]
@nickmew0 - thank YOU for troubleshooting and contributing to the add-on! 🙂 

As next step, I'd kindly ask you to edit `$SPLUNK_HOME/etc/apps/TA-zenoss/lib/zenoss_api.py` as following

```
@@ -107,7 +107,8 @@ class ZenossAPI():
         if response.status_code != 200:
             raise Exception("Unable to complete request. HTTP Error [{}]: {}".format(
                 response.status_code,
-                payload,
+                # payload,
+                response.text
             ))

         return response.json()
```
In this way, an explanation about the 400 error thrown by Zenoss should be provided.

**Comment by nickmew0** [comment]
I'll go ahead and do that - but I just realised that I'd not clicked on the 'Disable SSL Validation' when  I got that message - for our Splunk development server I would expect to need to do that as it doesn't have a valid SSL certification on it.
When I DO disable the SSL validation I get 
Encountered the following error while trying to save: Failed to connect to https://atosdb.zenoss.eu and query. Error expected str, bytes or os.PathLike object, not int

I'll make the change you suggested above and try with the option on and off as well

**Comment by nickmew0** [comment]
Hi - having changed the code I now get

Encountered the following error while trying to save: Failed to connect to https://atosdb.zenoss.eu and query. Error Unable to complete request. HTTP Error [400]: <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>POST object expects Content-Type multipart/form-data</Details></Error>

when the Disable SSL Validation is NOT switched on, but this may not be the issues

When switching Disable SSL Validation ON, still get the same error as above
Encountered the following error while trying to save: Failed to connect to https://atosdb.zenoss.eu and query. Error expected str, bytes or os.PathLike object, not int

We know when we tried embedding the curl command that worked using the Splunk Add-on builder we had to disable SSL validation to get any data back

**Comment by edro15** [comment]
thanks again for reporting those issues and performing tests. I think the issue with "Disable SSL Validation" = ON could be fixed with the following patch at `$SPLUNK_HOME/etc/apps/TA-zenoss/bin/zenoss_events.py`

```
@@ -318,7 +318,7 @@ lastTime %s -- skipping" % (evid, last_time)
         username = validation_definition.parameters["zenoss_username"]
         zenoss_realm = validation_definition.parameters["zenoss_realm"]
         zenoss_server = validation_definition.parameters["zenoss_server"]
-        no_ssl_cert_check = int(validation_definition.parameters["no_ssl_cert_check"])
+        no_ssl_cert_check = bool(int(validation_definition.parameters["no_ssl_cert_check"]))
         cafile = validation_definition.parameters["cafile"]
         interval = validation_definition.parameters["interval"]
         start_date = validation_definition.parameters["start_date"]
@@ -385,7 +385,7 @@ for reference")
         zenoss_server = input_items.get("zenoss_server")
         username = input_items.get("zenoss_username")
         zenoss_realm = input_items.get("zenoss_realm")
-        no_ssl_cert_check = input_items.get("no_ssl_cert_check")
+        no_ssl_cert_check = bool(int(input_items.get("no_ssl_cert_check")))
         cafile = input_items.get("cafile")
         interval = int(input_items.get("interval", HOUR))
         start_date = input_items.get("start_date")
```
If you feel like trying it out, please let me know how it goes.

Case of "Disable SSL Validation" = OFF throwing `400 InvalidArgument` is still unresolved. So you're saying in that case `Content-Type: multipart/form-data` shall be used? is this documented anywhere?

**Comment by nickmew0** [comment]
ok, will have a go at the SSL validation patch and see what happens . Will then look into any documentation  / details re: the multipart/form-data - I d have a contact at Zenoss who may be able to help

**Comment by nickmew0** [comment]
OK - so the SSL patch works - now getting the same reponse with that on, but I've changed one more paramater and have got data feeding in:
Our original test curl command had a full path to the specific api https://OURDOMAIN.zenoss.eu/cz0/zport/dmd/evconsole_router

So I tried adding some of the full path in - and using https://OURDOMAIN.zenoss.eu/cz0/zport fo the Zenoss  URL brought in data. Now whether this is the correct qualification (i.e. whether it would still work with more or less of the path) I don't know, as this is the first one I tried. 
Now need to check and see if we are getting what we expected. 
Thanks for you help, will let you know how we get on

**Comment by edro15** [comment]
@nickmew0 - Thanks for your help. 

I collected fixes related to this issue in [this PR](https://github.com/edro15/splunk-add-on-for-zenoss/pull/2). Whenever you have a moment, I'd really appreciate if you could have a look. Thanks again for your support.

**Comment by nickmew0** [comment]
Reviews all the code - alll looks good, thanks for your help!
